### PR TITLE
um. probably a better way

### PR DESCRIPTION
**Pull request by insberr**
Lets add wall support. Woo.
- horizontal and angled walls do not work yet

### CODE REVIEW

**Comment by insberr** [comment]
walls should be { sx: num, sy: num, ex: num, ey: num } and then all the points in between can be generated in the raycast when adding to the matrix. Time for some algebra woooo.

**Comment by webmsgr** [comment]
Time to gut the entire ray casting code. Joy

**Comment by webmsgr** [comment]
We need MORE TESTS

**Comment by insberr** [comment]
Fix walls first so we can add wall tests

**Comment by insberr** [comment]
because i told you they dont work. they dont work on the map visual

**Comment by webmsgr** [comment]
Somehow visualizing every step of the raycast would be really nice,  but I have no idea how to do that without putting a bunch of hooks into the raycast function .

**Comment by insberr** [comment]
seperate each part of the raycast function into multiple functions and then make on raycast function that combines them all. but then you can call each function seperatly for the visualization?

**Comment by webmsgr** [comment]
all tests pass -> merge?

**Comment by insberr** [comment]
Next up, fixing the edges. We should probably merge this tho since walls work now.

**Comment by insberr** [comment]
Ill wait for pretty to be merged.

**Pull request merged**
